name: wms_pro
description: Multi-warehouse WMS MVP (Web + Windows)
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  shared_preferences: ^2.3.2

  pluto_grid: ^8.0.0
  collection: ^1.18.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  appwrite: ^20.3.2
  connectivity_plus: ^7.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  generate: true
  uses-material-design: true


